networks:
  workhub_network:
    driver: bridge

services:
  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    restart: unless-stopped
    networks:
      - workhub_network

  azurite:
    image: mcr.microsoft.com/azure-storage/azurite
    container_name: azurite
    ports:
      - "10000:10000"
    volumes:
      - azurite_data:/data
    restart: unless-stopped
    networks:
      - workhub_network

  mailhog:
    image: mailhog/mailhog
    container_name: mailhog
    ports:
      - "1025:1025"
      - "8025:8025"
    volumes:
      - mailhog_data:/data
    restart: unless-stopped
    networks:
      - workhub_network

  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: mongopass
    restart: unless-stopped
    networks:
      - workhub_network
  
  postgres_identity:
    image: postgres:latest
    container_name: postgres_identity
    ports:
      - "5432:5432"
    volumes:
      - postgres_identity_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: passpass
      POSTGRES_DB: IdentityServiceDb
    restart: unless-stopped
    networks:
      - workhub_network

  postgres_primary:
    image: postgres:latest
    container_name: postgres_primary
    ports:
      - "5433:5432"
    volumes:
      - postgres_primary_data:/var/lib/postgresql/data
      - ./DockerConfig/InitPostgresPrimaryDb/init-primary.sh:/docker-entrypoint-initdb.d/init-primary.sh
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: passpass_primary
      POSTGRES_DB: ProjectsServiceDb
    restart: unless-stopped
    networks:
      - workhub_network

  postgres_replica:
    image: postgres:latest
    container_name: postgres_replica
    ports:
      - "5434:5432"
    volumes:
      - postgres_replica_data:/var/lib/postgresql/data
      - ./DockerConfig/InitPostgresReplicaDb/init-replica.sh:/docker-entrypoint-initdb.d/init-replica.sh
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: passpass_replica
      POSTGRES_DB: ProjectsServiceDb
    depends_on:
      - postgres_primary
    restart: unless-stopped
    networks:
      - workhub_network
    command: ["/bin/bash", "/docker-entrypoint-initdb.d/init-replica.sh"]
  
  postgres_hangfire:
    image: postgres:latest
    container_name: postgres_hangfire
    ports:
      - "5435:5432"
    volumes:
      - postgres_hangfire_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: passpass
      POSTGRES_DB: ProjectsServiceHangfireDb
    restart: unless-stopped
    networks:
      - workhub_network

  workhub_apigateway:
    build:
      context: .
      dockerfile: Backend/ApiGateway/Dockerfile
    container_name: workhub_apigateway
    ports:
      - "5000:5000"
      - "7000:7000"
    volumes:
      - ./Backend/ApiGateway/https/aspnetapp.pfx:/https/aspnetapp.pfx:ro
    restart: unless-stopped
    networks:
      - workhub_network

  workhub_identityservice:
    build:
      context: .
      dockerfile: Backend/IdentityService/Dockerfile
    container_name: workhub_identityservice
    ports:
      - "5080:5080"
      - "7080:7080"
    volumes:
      - ./Backend/ApiGateway/https/aspnetapp.pfx:/https/aspnetapp.pfx:ro
    restart: unless-stopped
    networks:
      - workhub_network
    depends_on:
      - postgres_identity

  workhub_projectsservice:
    build:
      context: .
      dockerfile: Backend/ProjectsService/Dockerfile
    container_name: workhub_projectsservice
    ports:
      - "5081:5081"
      - "7081:7081"
    volumes:
      - ./Backend/ApiGateway/https/aspnetapp.pfx:/https/aspnetapp.pfx:ro
    restart: unless-stopped
    networks:
      - workhub_network
    depends_on:
      - postgres_hangfire
      - postgres_primary
      - postgres_replica

  workhub_chatservice:
    build:
      context: .
      dockerfile: Backend/ChatService/Dockerfile
    container_name: workhub_chatservice
    ports:
      - "5082:5082"
      - "7082:7082"
    volumes:
      - ./Backend/ApiGateway/https/aspnetapp.pfx:/https/aspnetapp.pfx:ro
    restart: unless-stopped
    networks:
      - workhub_network
    depends_on:
      - mongodb
  
  workhub_paymentsservice:
    build:
      context: .
      dockerfile: Backend/PaymentsService/Dockerfile
    container_name: workhub_paymentsservice
    ports:
      - "5083:5083"
      - "7083:7083"
    volumes:
      - ./Backend/ApiGateway/https/aspnetapp.pfx:/https/aspnetapp.pfx:ro
    restart: unless-stopped
    networks:
      - workhub_network

volumes:
  redis_data:
  azurite_data:
  mailhog_data:
  mongodb_data:
  postgres_identity_data:
  postgres_hangfire_data:
  postgres_primary_data:
  postgres_replica_data:
