services:
  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    environment:
      - REDIS_PASSWORD=redispass
    restart: unless-stopped

  azurite:
    image: mcr.microsoft.com/azure-storage/azurite
    container_name: azurite
    ports:
      - "10000:10000"
    volumes:
      - azurite_data:/data
    restart: unless-stopped

  mailhog:
    image: mailhog/mailhog
    container_name: mailhog
    ports:
      - "1025:1025"
      - "8025:8025"
    volumes:
      - mailhog_data:/data
    restart: unless-stopped

  workhub_apigateway:
    build:
      context: .
      dockerfile: Backend/ApiGateway/Dockerfile
    container_name: workhub_apigateway
    ports:
      - "5000:5000"
      - "7000:7000"
    environment:
      ASPNETCORE_URLS: "https://+:7000;http://+:5000"
      ASPNETCORE_Kestrel__Certificates__Default__Path: "/https/aspnetapp.pfx"
      ASPNETCORE_Kestrel__Certificates__Default__Password: "HttpsPassword"
    volumes:
      - ./Backend/ApiGateway/https/aspnetapp.pfx:/https/aspnetapp.pfx:ro
    restart: unless-stopped

volumes:
  redis_data:
  azurite_data:
  mailhog_data:
