namespace ProjectsService.Application.UseCases.Queries.FreelancerApplicationUseCases.GetFreelancerApplicationById;

public sealed record GetFreelancerApplicationByIdQuery(Guid FreelancerId, Guid ApplicationId) : IRequest<FreelancerApplication>;