namespace ProjectsService.Application.UseCases.Commands.FreelancerApplicationUseCases.DeleteFreelancerApplication;

public record DeleteFreelancerApplicationCommand(Guid FreelancerId, Guid ApplicationId) : IRequest;